### ISSUE TITLE
[bug] deploy.ErrorCheck usage is unclear

### ISSUE THREAD

**Issue by ryandeivert** [OktaSecurityLabs/sgt#6]
### Background

The `deploy` package contains an `ErrorCheck` function that is used a handful of times within the package and within the `main` package. The usage of this function is unclear, since it both logs the err using the `Error` level, and then also logs the err as `Fatal` level, which will both print the error and call `Exit(1)`. The main issue is that there are multiple locations that the calls to this expect the error to be returned if one exists. For instance, [this call](https://github.com/OktaSecurityLabs/sgt/blob/e1857b87309f9d7f297f679cabdeb2202749dfd7/handlers/deploy/deploy.go#L144-L146) would never actually have an effect since the program would have exited at the point of entering this if block. The offending code is [here](https://github.com/OktaSecurityLabs/sgt/blob/e1857b87309f9d7f297f679cabdeb2202749dfd7/handlers/deploy/deploy.go#L66).

### Requested Changes

I think the idea of this function is to be a helper to make error checking/logging/returning easier. However, it should be made clear if this function should be exiting or just logging the error and returning it. If I get some clarification on the desired functionality, I'd be happy to put up a PR to address this.

**Comment by securityclippy** [comment]
Sadly this is just the result of lack of time to clean it up.  The CheckError func was intended to exit on error as well as log the error for analysis later.  The idea behind it being that during deploy, any error in terraform should cause the problem to halt instead of continuing on with the rest the terraforming.

Would love a PR, but I'm also happy to clean up my own mess.  It's definitely very ugly =(

**Comment by ryandeivert** [comment]
@securityclippy thanks for the clarification! so long as the end result is that it's supposed to exit, it should be fairly easy to clean up. feel free to assign to me :)
